packages:
  - packages/**
  - '!**/test/**'

allowBuilds:
  esbuild: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - '@types/mithril@2.2.9'
  - slimdown-js@1.5.0

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

patchedDependencies:
  mithril-markdown-wysiwyg@0.2.3: patches/mithril-markdown-wysiwyg@0.2.3.patch
